Update with various features

diff --git a/.chezmoiscripts/run_onchange_after_config.sh.tmpl b/.chezmoiscripts/run_onchange_after_config.sh.tmpl
--- a/.chezmoiscripts/run_onchange_after_config.sh.tmpl
+++ b/.chezmoiscripts/run_onchange_after_config.sh.tmpl
@@ -4,27 +4,36 @@
 {{ end -}}
 
 {{ if eq .osid "linux-fedora" -}}
-#!/bin/bash
+  #!/bin/bash
 
-set -eufo pipefail
-
-# solaar
-sudo cp ~/.local/share/chezmoi/assets/42-logitech-unify-permissions.rules /etc/udev/rules.d/.
-{{ $sudo }} udevadm control --reload-rules
+  set -eufo pipefail
 
 
-# Docker
-if ! getent group docker > /dev/null 2>&1; then
-  {{ $sudo }} groupadd docker
-fi
-if ! groups $USER | grep -q "\bdocker\b"; then
-  {{ $sudo }} usermod -aG docker $USER
-  newgrp docker
-fi
 
-{{ $sudo }} systemctl enable docker
-{{ $sudo }} systemctl start docker
+  # Docker
+  if ! getent group docker > /dev/null 2>&1; then
+    {{ $sudo }} groupadd docker
+  fi
+  if ! groups $USER | grep -q "\bdocker\b"; then
+    {{ $sudo }} usermod -aG docker $USER
+    newgrp docker
+  fi
 
+  {{ $sudo }} systemctl enable docker
+  {{ $sudo }} systemctl start docker
+
+  {{ if not .headless -}}
+    # solaar
+    sudo cp ~/.local/share/chezmoi/assets/42-logitech-unify-permissions.rules /etc/udev/rules.d/.
+    {{ $sudo }} udevadm control --reload-rules
+
+    if ! onedrive; then
+      echo "onedrive command failed, but continuing..."
+    fi
+
+    systemctl --user enable onedrive
+    systemctl --user start onedrive 
+  {{ end -}}
 {{ end -}}
 
-echo "Should be finished. You might wanna consider restarting."
+echo "Should be finished. Setup Onedrive auth by running "onedrive". You might wanna consider restarting."
